version: '3'

services:

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: always
  
  db:
    container_name: db
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    restart: always